### ISSUE TITLE
[Bug] non-critical error on Anki 23.10.1

### ISSUE THREAD

**Issue by Exponent4806** [BlueGreenMagick/Review-Hotmouse#23]
I use the default parameters for the add-on, and I get the following error several times per day:

OS: EndeavourOS (Arch Linux)

---
**Debug Info:**
Anki 23.10.1 (fac9e0ee) Python 3.11.6 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.6.6-arch1-1-x86_64-with-glibc2.38
Flags: frz=False ao=True sv=3
Add-ons, last update check: 2023-12-12 21:01:15
Add-on involved: ⁨Review Hotmouse⁩

**Caught exception:**
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/main.py", line 148, in eventFilter
    if handled := super().eventFilter(obj, evt):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anki/hooks.py", line 89, in decorator_wrapper
    return repl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anki/hooks.py", line 86, in repl
    return new(_old=old, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/.local/share/Anki2/addons21/1928346827/event.py", line 272, in event_filter
    if manager.on_mouse_press(event):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/.local/share/Anki2/addons21/1928346827/event.py", line 232, in on_mouse_press
    hotkey_str = self.build_hotkey(btns, click=pressed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/.local/share/Anki2/addons21/1928346827/event.py", line 196, in build_hotkey
    shortcut_key_str += "_click_{}".format(click.name)
    ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'shortcut_key_str' where it is not associated with a value

---

It is possible to ignore the error and simply continue working. However, it is quite frustrating to stop the Anki reviews unnecesarily...

It is just a minor issue. I hope the data could be useful...! **Thanks for your great job !**

**Comment by BlueGreenMagick** [comment]
Fixed!
